import { createClient } from "@/lib/supabase/server";
import { CreateTestInput } from "@/lib/validations/test";
import { getAuthenticatedUserWithRoles } from "./auth.service";

export interface TestMaster {
  id: string;
  serial_no: string;
  discipline_group: string;
  material_product: string;
  component_parameter: string;
  specific_test: string;
  test_method: string;
  technique_equipment: string;
  is_nabl: boolean | null;
  category: "Construction" | "Environmental" | null;
  created_at: string;
  created_by: string | null;
  updated_at: string;
  updated_by: string | null;
}

export const testService = {
  async createTestMaster(data: CreateTestInput) {
    try {
      const user = await getAuthenticatedUserWithRoles();
      if (!user) return { success: false, error: "Unauthorized" };

      const supabase = await createClient();

      // Auto-generate serial number
      const { count } = await supabase
        .from("test_master")
        .select("*", { count: "exact", head: true });
        
      const nextId = (count || 0) + 1;
      const autoGeneratedSerial = `TM-${nextId.toString().padStart(4, "0")}`;

      const { data: testData, error } = await supabase
        .from("test_master")
        .insert({
          serial_no: autoGeneratedSerial,
          discipline_group: data.discipline_group,
          material_product: data.material_product,
          component_parameter: data.component_parameter,
          specific_test: data.specific_test || "",
          test_method: data.test_method,
          technique_equipment: data.technique_equipment || "",
          is_nabl: data.is_nabl ?? false,
          category: data.category || "",
          created_by: user.id,
          updated_by: user.id,
        })
        .select()
        .single();

      if (error) {
        console.error("Error creating test master:", error);
        return { success: false, error: error.message };
      }

      return { success: true, data: testData as TestMaster };
    } catch (error: any) {
      console.error("Error creating test master:", error);
      return { success: false, error: "An unexpected error occurred" };
    }
  },

  async getTests() {
    try {
      const user = await getAuthenticatedUserWithRoles();
      if (!user) return { success: false, error: "Unauthorized" };

      const supabase = await createClient();
      const { data, error } = await supabase
        .from("test_master")
        .select("id, serial_no, discipline_group, material_product, component_parameter, specific_test, test_method, technique_equipment, is_nabl, category, created_at, created_by, updated_at, updated_by")
        .order("created_at", { ascending: false });

      if (error) {
        console.error("Error fetching tests:", error);
        return { success: false, error: error.message };
      }

      return { success: true, data: data as TestMaster[] };
    } catch (error: any) {
      console.error("Error fetching tests:", error);
      return { success: false, error: "An unexpected error occurred" };
    }
  }
};
