ALTER TABLE test_master
ADD COLUMN IF NOT EXISTS particulars TEXT,
ADD COLUMN IF NOT EXISTS unit TEXT,
ADD COLUMN IF NOT EXISTS sample_size TEXT,
ADD COLUMN IF NOT EXISTS minimum_value TEXT,
ADD COLUMN IF NOT EXISTS time_required TEXT,
ADD COLUMN IF NOT EXISTS tested_as_per_is TEXT;
